Location.create(name: "La Jodida", city: "Begur", country: "Spain" )
Location.create(name: "Sagrada Familia", city: "Barcelona", country: "Spain" )
Location.create(name: "El pillao", city: "Girona", country: "Spain" )
Location.create(name: "Los monges", city: "Tarragona", country: "Norway" )
Location.create(name: "Porta Ventura", city: "Tarragona", country: "USA" )
Location.create(name: "La Maria", city: "Estartit", country: "Spain" )
